name: Bug Report
description: Report a reproducible bug in backend or docs/runtime workflows
title: "[bug] "
labels:
  - bug
body:
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - backend/agent
        - docs
        - ci/cd
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened vs what you expected?
      placeholder: concise bug summary
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / stack trace
      render: shell
  - type: textarea
    id: env
    attributes:
      label: Environment
      placeholder: OS, Python/Node version, commit hash
