name: Feature Request
description: Propose a focused enhancement
title: "[feature] "
labels:
  - enhancement
body:
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - backend/agent
        - docs
        - tooling
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Keep it concrete and minimal.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I checked existing issues and docs first
          required: true
